# Generated by Django 4.2.1 on 2023-05-23 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shapeCode', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('diameter', models.FloatField()),
                ('height', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/items/')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.code')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialOutgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.measurementunit')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialIncoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('challanNo', models.CharField(max_length=100)),
                ('challanDate', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.measurementunit')),
            ],
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.section'),
        ),
        migrations.CreateModel(
            name='MachineCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.itemname')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.machine')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.measurementunit')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.section'),
        ),
        migrations.CreateModel(
            name='JiggerProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.PositiveIntegerField(choices=[(1, 'A Shift'), (2, 'B Shift'), (3, 'C Shift')])),
                ('quantity', models.PositiveIntegerField()),
                ('forming_loss', models.PositiveIntegerField()),
                ('production_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.itemname')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.machine')),
            ],
        ),
        migrations.AddField(
            model_name='itemname',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.shape'),
        ),
    ]
